### ISSUE TITLE
Be careful about third party libraries

### ISSUE THREAD

**Issue by enisn** [iyzico/iyzipay-dotnet#83]
There is some other libraries that can steal sensitive information of user's apps. 

<a href="https://ibb.co/bXS5GrS"><img src="https://i.ibb.co/pdtjk3t/screen-05.png" alt="screen-05" border="0"></a>

You may report them and remvoe from NuGet, Most of people can use other libraries by mistake. And that libraries can steal sensitive data by sending to their owners before sending iyzico.

 - [IyzipayCore](https://www.nuget.org/packages/IyzipayCore/)

 - [Iyzipay.Core](https://www.nuget.org/packages/Iyzipay.Core/)

**Comment by yyenigun** [comment]
Thank you for your attention. We support open-source contributions and community can develop their own clients. Actually we don't officially have dotnet core support and that's why community develops their own dotnet-core clients. We will look at the pull requests and add dotnet-core support officially. Our security team always checks third-party libraries and we will also recheck these third party libraries for security purposes. Thank you for your support.

**Comment by enisn** [comment]
> Thank you for your attention. We support open-source contributions and community can develop their own clients. Actually we don't officially have dotnet core support and that's why community develops their own dotnet-core clients. We will look at the pull requests and add dotnet-core support officially. Our security team always checks third-party libraries and we will also recheck these third party libraries for security purposes. Thank you for your support.

So, can we trust these .Net Core libraries for now and future?

**Comment by yyenigun** [comment]
We don't have official .Net Core support for now and our customers implement their own clients for our JSON API. The community uses these clients but it is the choice of community. We don't officially support third-party clients so we can not officially say that you can trust these .Net Core libraries. You can implement your own .Net Core library if you don't trust community libraries. We are also working on .Net Core support in a backward compatible way.
